### ISSUE TITLE
Excellent Project

### ISSUE THREAD

**Issue by lockhartsoftware** [DonnellHarris/Kanban-2024#1]
Hi Donnell,

This is an excellent piece of work: well designed, documented and implemented.

I am attempting to get the project running locally on my laptop.

I configured Multiple Startup Projects: KanbanApi and KanbanBlazor.

When I run the app, it is asking for a ClientID.

What do I need to configure in Azure to create this ClientID and also ClientSecret?

Thanks.

**Comment by DonnellHarris** [comment]
Hi Walter,

I appreciate the kind words. However, the project is not complete. It is currently being developed for a class project and won't be finished until the end of next month. The Kanban portion of the UI has not even been implemented yet. The documentation was created before development began and some minor changes have occurred. 

To answer your question more directly, the Blazor app uses Microsoft Identity for authentication/authorization, which requires registering the app in the Microsoft Entra Id portal on Azure. That is where I obtained the ClientId and Client Secret.

If you are interested in getting the completed project with full instructions, please check back in about a month.

Thanks,
Don
